GET http://localhost:99/api/v1/filedata/get_file_by_user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YWh5dSIsImlhdCI6MTY5ODgwNzkwNSwiZXhwIjoxNjk4ODA5MzQ1fQ.lhhpAONPH0vv7o8eGFueBu6msQflIeoZJgPz_lLTDXk