GET http://localhost:99/api/v1/filedata/get_file_by_user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YWh5dSIsImlhdCI6MTY5ODQ3NjM4MSwiZXhwIjoxNjk4NDc3ODIxfQ.vvb9VBYjXWow5kuZLpJoVoWZGIXevUtwo0rwhiJP8Mc